- name: Sync and merge upstream repository with your current repository
  uses: dabreadman/sync-upstream-repo@v1.3.
  with:
    # URL of gitHub public upstream repo
    upstream_repo: "https://github.com/no-cmyk/Search-Engine-Spam-Blocklist"
    # Branch to merge from upstream (defaults to downstream branch)
    upstream_branch: master
    # Branch to merge into downstream
    downstream_branch: master
    # GitHub Bot token
    token: ${{ secrets.GITHUB_TOKEN }}
  on:
    workflow_dispatch:
    schedule: 
    - cron: "0 13 * * 1"
